# ------------------------

# replaceHostiles: replaces *SOME* hostile mobs with zombies
replaceHostiles: false

# extraSpawns: spawn extra zombies
extraSpawns: true

# endSpawn: replace 12,5% of endermen with zombies in The End
endSpawn: true

# displayType: show the zombie's type as the zombie's nametag
displayType: false

# zombifiedPiglinAttack: makes Zombified Piglins attack players without players having to attack them first.
zombifiedPiglinAttack: true

# zombifiedPiglinRadius: half of the area that the Zombified Piglin will look after players.
zombifiedPiglinRadius: 16